### ISSUE TITLE
Checkout: c2a_config is not defined.

### ISSUE THREAD

**Issue by cheelahim** [craftyclicks/magento2#5]
There is an issue with the configuration. The checkout is broken after module installation if access token is not specified. The js config (c2a_config) is not generated correctly with empty token even if module is disabled.
Platform: Magento 2.0.5 EE
### Steps to reproduce:
1. Install the module
2. Add product to cart
3. Proceed to checkout
### Expected result:

Checkout shipping details form appears.
### Actual result:

White screen.  c2a_config is not defined error fired.

**Comment by gs-mancs** [comment]
Could not reproduce this on said version. (GitHub version)

Here's how it should work:
If you didn't set anything, it should immediately grab a default value (xxxxx-xxxxx-xxxxx-xxxxx)
If you set it to empty string, it should still be okay.

I'll presume that this comes from the same issue as #6 
Since the data format on that EE downloadable version doesn't allow empty values, it might cause the whole php helper to collapse around line 30. (helper/data.php)

I'll extend the code so that it first gets the value, then makes sure that it's not broken / empty. (since after that it immediately calls the decrypt function...)

I'm a bit disappointed that I already have to start modifying code to handle Magento packaging issues...

**Comment by gs-mancs** [comment]
Could you please re-check this issue?

I swapped around an incorrectly nested function, and suddenly this issue disappeared on the EE downloadable package.

I wouldn't call it a fix per se, but it did seem to get rid of this bug.

Also, please note that the installation steps now include a full re-compile, as new Magento 2 versions started to require this in order to set all default values to the extension correctly.

**Comment by cheelahim** [comment]
Thank you @blindmancs. I'm using M2.0.6 EE installed via composer. I will let you know if I reproduce the bug on this version.

**Comment by cheelahim** [comment]
@blindmancs I couldn't reproduce the issue after update. This was a required fix https://github.com/craftyclicks/magento2/commit/01c7814d8bde3979af7878dce3919956c276b2eb#diff-735f70c1f948ebbd90915b1548d93432R30
Without escaping we got decrypted 'xxxxx-xxxxx-xxxxx-xxxxx' which broke the json.
This could be closed I believe.
